services:
  mongodb:
    image: mongo:6.0  # Use the latest MongoDB version
    container_name: mongodb
    ports:
      - "27017:27017" # Exposes MongoDB on localhost:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db # Persistent storage
      - mongodb_config:/data/configdb
    networks:
      - tech-radar

  mongo-express:
    image: mongo-express:1.0.0-alpha.4 # Web-based MongoDB GUI
    container_name: mongo-express
    ports:
      - "8081:8081" # Exposes Mongo Express on localhost:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: unless-stopped
    networks:
      - tech-radar

volumes:
  mongodb_data:
  mongodb_config:

networks:
  tech-radar:
    name: tech-radar
